"""
Framework-agnostic DAO protocol interfaces.

All DAO protocols depend on DatabaseSession, NOT on any specific ORM.
Service layer and API layer code exclusively against these protocols.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional, Protocol
from uuid import UUID

from dao_service.core.database import DatabaseSession
from dao_service.schemas.conversation import ConversationCreateDTO, ConversationDTO, ConversationUpdateDTO
from dao_service.schemas.demo_flag import DemoFlagCreateDTO, DemoFlagDTO
from dao_service.schemas.goal import GoalCreateDTO, GoalDTO, GoalUpdateDTO
from dao_service.schemas.milestone import MilestoneCreateDTO, MilestoneDTO, MilestoneUpdateDTO
from dao_service.schemas.task import TaskCreateDTO, TaskDTO, TaskUpdateDTO
from dao_service.schemas.enums import TaskState
from dao_service.schemas.user import UserCreateDTO, UserDTO, UserUpdateDTO


# --- Base CRUD Protocol ---


class BaseDAOProtocol(Protocol):
    """Minimum CRUD contract all DAOs must satisfy."""

    async def get_by_id(self, db: DatabaseSession, id: UUID) -> Optional[Any]: ...
    async def get_multi(self, db: DatabaseSession, skip: int, limit: int) -> List[Any]: ...
    async def count(self, db: DatabaseSession) -> int: ...
    async def delete(self, db: DatabaseSession, id: UUID) -> bool: ...


# --- Entity-specific Protocols ---


class UserDAOProtocol(Protocol):
    async def create(self, db: DatabaseSession, obj_in: UserCreateDTO) -> UserDTO: ...
    async def get_by_id(self, db: DatabaseSession, id: UUID) -> Optional[UserDTO]: ...
    async def get_multi(self, db: DatabaseSession, skip: int, limit: int) -> List[UserDTO]: ...
    async def count(self, db: DatabaseSession) -> int: ...
    async def update(self, db: DatabaseSession, id: UUID, obj_in: UserUpdateDTO) -> Optional[UserDTO]: ...
    async def delete(self, db: DatabaseSession, id: UUID) -> bool: ...


class GoalDAOProtocol(Protocol):
    async def create(self, db: DatabaseSession, obj_in: GoalCreateDTO) -> GoalDTO: ...
    async def get_by_id(self, db: DatabaseSession, id: UUID) -> Optional[GoalDTO]: ...
    async def get_multi(self, db: DatabaseSession, skip: int, limit: int) -> List[GoalDTO]: ...
    async def count(self, db: DatabaseSession) -> int: ...
    async def update(self, db: DatabaseSession, id: UUID, obj_in: GoalUpdateDTO) -> Optional[GoalDTO]: ...
    async def delete(self, db: DatabaseSession, id: UUID) -> bool: ...
    async def get_with_relations(self, db: DatabaseSession, id: UUID) -> Optional[Dict[str, Any]]: ...


class MilestoneDAOProtocol(Protocol):
    async def create(self, db: DatabaseSession, obj_in: MilestoneCreateDTO) -> MilestoneDTO: ...
    async def get_by_id(self, db: DatabaseSession, id: UUID) -> Optional[MilestoneDTO]: ...
    async def get_multi(self, db: DatabaseSession, skip: int, limit: int) -> List[MilestoneDTO]: ...
    async def count(self, db: DatabaseSession) -> int: ...
    async def update(
        self, db: DatabaseSession, id: UUID, obj_in: MilestoneUpdateDTO
    ) -> Optional[MilestoneDTO]: ...
    async def delete(self, db: DatabaseSession, id: UUID) -> bool: ...


class TaskDAOProtocol(Protocol):
    """Framework-agnostic task DAO interface with custom Scheduler/Observer queries."""

    # Standard CRUD
    async def create(self, db: DatabaseSession, obj_in: TaskCreateDTO) -> TaskDTO: ...
    async def get_by_id(self, db: DatabaseSession, id: UUID) -> Optional[TaskDTO]: ...
    async def get_multi(self, db: DatabaseSession, skip: int, limit: int) -> List[TaskDTO]: ...
    async def count(self, db: DatabaseSession) -> int: ...
    async def update(self, db: DatabaseSession, id: UUID, obj_in: TaskUpdateDTO) -> Optional[TaskDTO]: ...
    async def delete(self, db: DatabaseSession, id: UUID) -> bool: ...

    # Custom methods for Scheduler microservice
    async def get_tasks_by_user_and_timerange(
        self, db: DatabaseSession, user_id: UUID, start_time: datetime, end_time: datetime
    ) -> List[TaskDTO]: ...

    async def update_calendar_event_id(
        self, db: DatabaseSession, task_id: UUID, calendar_event_id: str
    ) -> Optional[TaskDTO]: ...

    async def bulk_update_state(
        self, db: DatabaseSession, task_ids: List[UUID], new_state: TaskState
    ) -> int: ...

    # Custom methods for Observer microservice
    async def get_task_statistics(
        self, db: DatabaseSession, user_id: UUID, start_date: datetime, end_date: datetime
    ) -> Dict[str, Any]: ...


class ConversationDAOProtocol(Protocol):
    async def create(
        self, db: DatabaseSession, obj_in: ConversationCreateDTO
    ) -> ConversationDTO: ...
    async def get_by_id(self, db: DatabaseSession, id: UUID) -> Optional[ConversationDTO]: ...
    async def get_multi(
        self, db: DatabaseSession, skip: int, limit: int
    ) -> List[ConversationDTO]: ...
    async def count(self, db: DatabaseSession) -> int: ...
    async def update(
        self, db: DatabaseSession, id: UUID, obj_in: ConversationUpdateDTO
    ) -> Optional[ConversationDTO]: ...


class DemoFlagDAOProtocol(Protocol):
    async def get_by_user_id(self, db: DatabaseSession, user_id: UUID) -> Optional[DemoFlagDTO]: ...
    async def upsert(self, db: DatabaseSession, obj_in: DemoFlagCreateDTO) -> DemoFlagDTO: ...
